apiVersion: v1
description: A helm for the Alfresco content connector driver runtime bundle
icon: https://secure.gravatar.com/avatar/4fa13c8f5c909e04561a81e4f3b887a9.jpg
name: alfresco-content-connector-driver
version: 0.0.1
